ModelParams:
  batchsize: 256
  earlystop: 5
  epochs: 100
  val_split: 0.1
RFParams:
  max_depth: 20
  n_est: 100
StockData:
  range: 5y
  ticker: NVDA
UserInput:
  buy_threshold: 0.1
  gain_window: 60
  sell_threshold: -0.1
  test_size: 60
