ModelParams:
  batchsize: 256
  earlystop: 5
  epochs: 100
  val_split: 0.1
StockData:
  range: 5y
  ticker: SPY
UserInput:
  buy_threshold: 0.1
  gain_window: 60
  sell_threshold: -0.1
  test_size: 60
XGBParams:
  max_depth: 8
  n_est: 100
